[build]
  command = "npm run build-base && cp -r pages/admin/adminFunctions dist/pages/admin/ && cp -r src dist/"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Handle specific API endpoints
[[redirects]]
  from = "/api/employee/*"
  to = "https://betcha-api.onrender.com/employee/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/guest/*"
  to = "https://betcha-api.onrender.com/guest/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/landing/*"
  to = "https://betcha-api.onrender.com/landing/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/property/*"
  to = "https://betcha-api.onrender.com/property/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/roles/*"
  to = "https://betcha-api.onrender.com/roles/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/faq/*"
  to = "https://betcha-api.onrender.com/faq/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/payment/*"
  to = "https://betcha-api.onrender.com/payment/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/payments/*"
  to = "https://betcha-api.onrender.com/payments/:splat"
  status = 200
  force = true

# Handle all other API calls
[[redirects]]
  from = "/api/*"
  to = "https://betcha-api.onrender.com/:splat"
  status = 200
  force = true

# Note: Removed SPA fallback that was interfering with API redirects and static files
# If you need SPA routing, add it back with proper conditions

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
