[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Handle specific API endpoints
[[redirects]]
  from = "/api/employee/*"
  to = "https://betcha-api.onrender.com/employee/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/landing/*"
  to = "https://betcha-api.onrender.com/landing/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/property/*"
  to = "https://betcha-api.onrender.com/property/:splat"
  status = 200
  force = true

# Handle all other API calls
[[redirects]]
  from = "/api/*"
  to = "https://betcha-api.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
